# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postfix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('source', 'destination', 'domain')]),
        ),
        migrations.AlterUniqueTogether(
            name='emailuser',
            unique_together=set([('username', 'domain')]),
        ),
    ]
